### ISSUE TITLE
直接运行exe错误

### ISSUE THREAD

**Issue by albert2lyu** [liuhao1946/RTT-T-Project#1]
Traceback (most recent call last):
  File "main.py", line 375, in <module>
  File "main.py", line 151, in main
  File "pylink\jlink.py", line 295, in __init__
TypeError: Expected to be given a valid DLL.
请问这个是需要什么库？

**Comment by lh-hg** [comment]
你缺失了JLinkARM.dll  

如果你安装了SEGGER的jlink软件，他会自动给你安装好，如果你没安装SEGGER，你需要单独下载这个dll并放在main.py目录下。

**Comment by albert2lyu** [comment]
可以了谢谢
